### ISSUE TITLE
Callback for QUnit ready and QUnit done

### ISSUE THREAD

**Issue by btamas** [ameshkov/node-qunit-puppeteer#11]
Hi,

first of all thank you for your work. It is a really nice tool :)
May I request a small improvement?
I would like to measure coverage with istanbul and I wrote a connect middleware for code instrument and code coverage post, but I have an issue, because my `QUnit.done()` callback runs after the tool's callback and sometimes I get the coverage info, but sometimes the `puppeteer` is closed before the POST request is finished.
So I would like to request 2 callbacks:
1. When QUnit is ready. (It would be nice to have) https://github.com/ameshkov/node-qunit-puppeteer/blob/master/index.js#L215
2. When QUnit tests are finished. (It would be mandatory for me) https://github.com/ameshkov/node-qunit-puppeteer/blob/master/index.js#L80

I would be totally satisfied with something like this:
```
if (window.onNodeQUnitPuppeteerDone) {
  window.onNodeQUnitPuppeteerDone().then(() => deferred.resolve(result));
} else {
  deferred.resolve(result);
}
```

I think it would be a good feature for others as well.

**Comment by ameshkov** [comment]
Got it, thank you!

I guess a temporary solution would be to use synchronous XHR to post the data. Meanwhile, I'll think about what can be done about it.

**Comment by btamas** [comment]
I created a PR about the requested modifications.
https://github.com/ameshkov/node-qunit-puppeteer/pull/12

**Comment by ameshkov** [comment]
@btamas sorry for the late reply, finally I've got some time to think about it.

There's an alternative solution that fits your needs and does not involve extending the library. 

You can do smth like this instead:
```
let realDone = QUnit.done;
QUnit.done = function(context) {
    doSomeAsyncWork().then(()=> { realDone.apply(QUnit, context); });
}
```

**Comment by btamas** [comment]
Your solution could work, but I do not know, where should I add rewrite of `QUnit.done`. When QUnit module loads, your `Object.defineProperty` setter extends QUnit and adds your callback. After that makes no sense to redefine it, because it is too late. I do not want to modify `QUnit` lib source. Could you explain where should I put your solution?

BTW, I found another possible solution, but it requires a small change in your code. This solution override your setter and define my `QUnit.done` earlier than yours. But it requires an extra line in your `Object.defineProperty`, to allow me to redefine property.
```js
{
  get: ...
  set: ...
  configurable: true
}
```
```js
const propertyDescriptor = Object.getOwnPropertyDescriptor(window, 'QUnit');
const originalSetter = propertyDescriptor && propertyDescriptor.set;
let qUnit;
Object.defineProperty(window, 'QUnit', {
  get : () => qUnit,
  set: (value) => {
    qUnit = value;
    defineCustomDone();
    if (originalSetter) {
      originalSetter(value);
    }
  }
});
```

**Comment by ameshkov** [comment]
Actually, I just realized that you can get directly to QUnit callbacks, this makes it even easier:

`QUnit.config.callbacks.done` returns an array of the `done` callbacks. So you can simply replace them all with your own wrapper.

**Comment by btamas** [comment]
It could work, but it is not documented in QUnit documentation, so I do not want to rely on that, because maybe they will change it in the future.
The other benefit of `defineProperty`, and I think this is why you also used that as well, is you should not know how and when the QUnit is loaded, because you will be notified in the setter. I'm using a http server middleware to inject my coverage post script and now I'm inserting my code before the `</body>` tag. But sometimes the QUnit is not loaded at this point, because our old code uses requirejs and the dependency load is asynchronous. So I would prefer to have a setter to get notification immediately, when QUnit is loaded and I would be able to define my done callback.
So if you do not mind, I would like to ask you to add `configurable: true` into your `defineProperty`. It will not at all affect you actual behavior, but it will help me a lot.

**Comment by ameshkov** [comment]
@btamas done, please check if this helps

**Comment by btamas** [comment]
It works like charm ;) Thank you @ameshkov !
