### ISSUE TITLE
Revert puppeteer upgrade

### ISSUE THREAD

**Issue by DanielRuf** [ameshkov/node-qunit-puppeteer#20]
https://github.com/ameshkov/node-qunit-puppeteer/blob/master/package.json#L20

https://github.com/ameshkov/node-qunit-puppeteer/commit/10cb1f0024c5390bc50ee0ce6e7a3e959fa7494b

This is a major version change which breaks many setups as Puppeteer 2.0.0 dropped support for Node 6. Please revert it and bump the major version of your library when you apply such a breaking change.

See https://github.com/puppeteer/puppeteer/releases/tag/v2.0.0

> Puppeteer now requires Node.js v8+; Node.js v6 is no longer supported

Related: https://github.com/DanielRuf/html-minifier-terser/issues/22

**Comment by ameshkov** [comment]
It makes sense, thank you!

**Comment by ameshkov** [comment]
Done.

v1.0.17 - puppeteer v1.9.0
v1.1.0 - puppeteer v2.1.0

**Comment by DanielRuf** [comment]
> v1.0.17 - puppeteer v1.9.0
> v1.1.0 - puppeteer v2.1.0

It should be the following as the default SemVer range `^` added by npm would also use v1.x (1.1, 1.2, 1.3, ...) unless npm uses `~` by default but this is not SemVer compliant.

x.y.z - x is for breaking changes, y for new features (no breaking changes) and z for patches (bugfixes).

https://semver.org/

So please make a v2.0.0 release that we can unpin the dependency in html-minifier-terser =)

**Comment by DanielRuf** [comment]
> v1.0.17 - puppeteer v1.9.0
> v1.1.0 - puppeteer v2.1.0

It should be the following as the default SemVer range `^` added by npm would also use v1.x (1.1, 1.2, 1.3, ...) unless npm uses `~` by default but this is not SemVer compliant.

x.y.z - x is for breaking changes, y for new features (no breaking changes) and z for patches (bugfixes).

https://semver.org/

So please make a v2.0.0 release that we can unpin the dependency in html-minifier-terser =)

It should be:
> v1.0.17 - puppeteer v1.9.0
> v2.0.0 - puppeteer v2.1.0

**Comment by ameshkov** [comment]
Yep, done

**Comment by DanielRuf** [comment]
It seems you did the same error again with 1.1.0 ;-)

https://github.com/ameshkov/node-qunit-puppeteer/commits/v1.1.0

**Comment by ameshkov** [comment]
Argh

Please check it now:)

**Comment by DanielRuf** [comment]
Thanks, this seems to be ok now =)

**Comment by DanielRuf** [comment]
Thanks, v1.1.1 seems to be ok now =)
