### ISSUE TITLE
Issues with the `redirectConsole` option

### ISSUE THREAD

**Issue by TiFu** [ameshkov/node-qunit-puppeteer#24]
Currently, the `redirectConsole` function fails to properly print objects in the browser context to the console leading to outputs like `jshandler@error` if `console.log` is used on exceptions/errors.

This can be fixed by changing the callback `console` registered on `page` in `index.js` according to the following code proposed by one of the maintainers of puppeteer:
 
https://github.com/puppeteer/puppeteer/issues/2083#issuecomment-380287424

Happy to provide a PR to fix this issue :-)

**Comment by ameshkov** [comment]
> Happy to provide a PR to fix this issue

Would be great, thank you!

**Comment by ameshkov** [comment]
Thank you!
