### ISSUE TITLE
Injecting `puppeteer.Page`

### ISSUE THREAD

**Issue by gusmd** [ameshkov/node-qunit-puppeteer#34]
Hi,

I have a use-case for this module that requires setting up an interceptor on the Puppeteer `Page` (using `page.setRequestInterception(true); page.on('request', ...)`). Additionally, I'll be running this on a AWS Lambda environment and so will depend on `chrome-aws-lambda` and `puppeteer-core` instead of `puppeteer` directly.

Unfortunately, the way `node-qunit-puppeteer` is written now isn't extensible enough for me to get around those two issues. One way I could still take advantage of this awesome module would be by having a `page` field on `QunitPuppeteerArgs`. `runQunitPuppeteer` could then do something like:

```
const browser = await (qunitPuppeteerArgs.page ? qunitPuppeteerArgs.page.browser() : puppeteer.launch(args));

try {
   const page = qunitPuppeteerArgs.page || await browser.newPage();
   // ...
```

Is this something you would be open to merging in? Also open to hearing about any other ideas you may have!

Thanks!

**Comment by ameshkov** [comment]
@gusmd thanks for opening this issue! I gave it a thought and it seems to be that slightly extending the public interface is the easiest solution here. Please check out the release notes: https://github.com/ameshkov/node-qunit-puppeteer/releases/tag/v2.1.0

Hopefully, it solves your issue.

**Comment by gusmd** [comment]
@ameshkov thanks for making these changes! It does solve my issue. The only quirk I had to overcome is that `node-qunit-puppeteer` still has `puppeteer` as a runtime dependency, so transitively my package inherits it, even though I don't really need it at runtime since I'm using `chrome-aws-lambda` and `puppeteer-core` to create the `browser`/`page` objects. This forces `npm` to download a full Chromium instance I don't need, so I'm using `puppeteer_skip_chromium_download=true` to skip that.

I'm not really sure what the best way to fix this on your side would be, but I thought you should know. Thanks again!
